# Generated by Django 5.2.6 on 2025-09-22 01:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('produce', 'Fresh Produce'), ('dairy', 'Dairy Products'), ('meat', 'Meat & Poultry'), ('seafood', 'Seafood'), ('bakery', 'Bakery Items'), ('frozen', 'Frozen Foods'), ('pantry', 'Pantry Staples'), ('beverages', 'Beverages'), ('prepared', 'Prepared Foods'), ('other', 'Other')], max_length=50, unique=True)),
                ('requires_refrigeration', models.BooleanField(default=False)),
                ('average_shelf_life_days', models.PositiveIntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('preferred_pickup_time_start', models.TimeField(default='08:00')),
                ('preferred_pickup_time_end', models.TimeField(default='12:00')),
                ('pickup_days', models.CharField(default='Mon-Fri', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('center_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('center_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_miles', models.PositiveIntegerField(default=35)),
                ('truck_capacity_pounds', models.PositiveIntegerField(default=2000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('quantity_pounds', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('sell_by_date', models.DateField(blank=True, null=True)),
                ('proposed_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('confirmed_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('actual_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('processed_from_email', models.BooleanField(default=False)),
                ('original_email_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbank.foodcategory')),
                ('grocery_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='foodbank.grocerystore')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='grocerystore',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_stores', to='foodbank.region'),
        ),
        migrations.CreateModel(
            name='FoodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('daily_average_need_pounds', models.PositiveIntegerField(help_text='Average daily food need in pounds')),
                ('storage_capacity_pounds', models.PositiveIntegerField(help_text='Maximum storage capacity in pounds')),
                ('can_self_pickup', models.BooleanField(default=False, help_text='Can pick up food independently')),
                ('open_time', models.TimeField(default='08:00')),
                ('close_time', models.TimeField(default='17:00')),
                ('operating_days', models.CharField(default='Mon-Fri', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_banks', to='foodbank.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField(default='08:00')),
                ('end_time', models.TimeField(default='12:00')),
                ('driver_team', models.CharField(help_text='Names of the 2-person driver team', max_length=200)),
                ('truck_identifier', models.CharField(max_length=50)),
                ('total_distance_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='foodbank.region')),
            ],
            options={
                'ordering': ['scheduled_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField()),
                ('stop_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=10)),
                ('estimated_arrival_time', models.TimeField()),
                ('actual_arrival_time', models.TimeField(blank=True, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=15)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('donations', models.ManyToManyField(blank=True, to='foodbank.fooddonation')),
                ('food_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodbank.foodbank')),
                ('grocery_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodbank.grocerystore')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='foodbank.deliveryroute')),
            ],
            options={
                'ordering': ['route', 'stop_order'],
            },
        ),
        migrations.CreateModel(
            name='EmailScheduleNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('pickup_proposal', 'Pickup Proposal'), ('delivery_proposal', 'Delivery Proposal'), ('pickup_confirmation', 'Pickup Confirmation'), ('delivery_confirmation', 'Delivery Confirmation'), ('schedule_change', 'Schedule Change'), ('cancellation', 'Cancellation')], max_length=25)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message_body', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('response_received', models.BooleanField(default=False)),
                ('response_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodbank.fooddonation')),
                ('route_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodbank.routestop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
