# Generated by Django 5.2.6 on 2025-09-29 00:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerDonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('container_type', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('proposed_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('confirmed_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='container_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of containers/packaging for this donation', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='donor_type',
            field=models.CharField(choices=[('grocery_store', 'Grocery Store'), ('restaurant', 'Restaurant')], default='grocery_store', max_length=20),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='grocery_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='foodbank.grocerystore'),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='container_donation',
            field=models.ForeignKey(blank=True, help_text='Associated container donation that offsets this cost', null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodbank.containerdonation'),
        ),
        migrations.CreateModel(
            name='ContainerSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('container_types', models.TextField(help_text='Types of containers supplied (boxes, bags, etc.)')),
                ('average_cost_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('minimum_donation_quantity', models.PositiveIntegerField(help_text='Minimum containers per donation')),
                ('donation_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_suppliers', to='foodbank.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='containerdonation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='foodbank.containersupplier'),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('cuisine_type', models.CharField(help_text='Type of cuisine (Italian, Mexican, etc.)', max_length=100)),
                ('seating_capacity', models.PositiveIntegerField(help_text='Number of seats')),
                ('daily_food_prep_pounds', models.PositiveIntegerField(help_text='Average daily food preparation in pounds')),
                ('typical_donation_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('container_cost_per_pound', models.DecimalField(decimal_places=2, help_text='Cost per pound for food containers/packaging', max_digits=6)),
                ('preferred_container_suppliers', models.TextField(blank=True, help_text='Preferred suppliers for food containers')),
                ('preferred_pickup_time_start', models.TimeField(default='15:00', help_text='After lunch service')),
                ('preferred_pickup_time_end', models.TimeField(default='18:00', help_text='Before dinner service')),
                ('pickup_days', models.CharField(default='Mon-Fri', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='foodbank.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='containerdonation',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_donations', to='foodbank.restaurant'),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_donations', to='foodbank.restaurant'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodbank.restaurant'),
        ),
    ]
